---
title: "Readr Package"
author: "David Asare Kumi"
date: "4/8/2020"
output: html_document
---


## Using the readr Package

- The readr package is recently developed by Hadley Wickham to deal with reading in large flat files quickly. The package provides replacements for functions like read.table() and read.csv(). The analogous functions in readr are read_table() and read_csv(). These functions are often much faster than their base R analogues and provide a few other nice features such as progress meters.

- For the most part, you can read use read_table() and read_csv() pretty much anywhere you might use read.table() and read.csv(). In addition, if there are non-fatal problems that occur while reading in the data, you will get a warning and the returned data frame will have some information about which rows/observations triggered the warning. This can be very helpful for “debugging” problems with your data before you get neck deep in data analysis.

- The importance of the read_csv function is perhaps better understood from an historical perspective. R’s built in read.csv function similarly reads CSV files, but the read_csv function in readr builds on that by removing some of the quirks and “gotchas” of read.csv as well as dramatically optimizing the speed with which it can read data into R. The read_csv function also adds some nice user-oriented features like a progress meter and a compact method for specifying column types.

- A typical call to read_csv will look as follows.

- library(tidyverse) ;library(readr)

- teams<-read_csv("data/teams_standings.csv")

- By default, read_csv will open a CSV file and read it in line-by-line. It will also (by default), read in the first few rows of the table in order to figure out the type of each column (i.e. integer, character, etc.). From the read_csv help page:

- You can specify the type of each column with the col_types argument.

- In general, it’s a good idea to specify the column types explicitly. This rules out any possible guessing errors on the part of read_csv. Also, specifying the column types explicitly provides a useful safety check in case anything about the dataset should change without you knowing about it.

- teams <- read_csv("data/team_standings.csv", col_types = "cc")

- Note that the col_types argument accepts a compact representation. Here "cc" indicates that the first column is character and the second column is character (there are only two columns). Using the col_types argument is useful because often it is not easy to automatically figure out the type of a column by looking at a few rows (especially if a column has many missing values).

- The read_csv function will also read compressed files automatically. There is no need to decompress the file first or use the gzfile connection function. The following call reads a gzip-compressed CSV file containing download logs from the RStudio CRAN mirror.

- logs <- read_csv("data/2016-07-19.csv.bz2", n_max = 10)

- Note that the warnings indicate that read_csv may have had some difficulty identifying the type of each column. This can be solved by using the col_types argument.

- logs <- read_csv("data/2016-07-19.csv.bz2", col_types = "ccicccccci", n_max = 10).

- You can specify the column type in a more detailed fashion by using the various col_* functions. For example, in the log data above, the first column is actually a date, so it might make more sense to read it in as a Date variable. If we wanted to just read in that first column, we could do

- logdates <- read_csv("data/2016-07-19.csv.bz2",  col_types = cols_only(date = col_date()),
n_max = 10)

- Now the date column is stored as a Date object which can be used for relevant date-related computations (for example, see the lubridate package).

- The read_csv function has a progress option that defaults to TRUE. This options provides a nice progress meter while the CSV file is being read. However, if you are using read_csv in a function, or perhaps embedding it in a loop, it’s probably best to set progress = FALSE.

- To accurately read a rectangular dataset with readr you combine two pieces: a function that parses the overall file, and a column specification. The column specification describes how each column should be converted from a character vector to the most appropriate data type, and in most cases it’s not necessary because readr will guess it for you automatically.

- readr supports seven file formats with seven read_ functions:

1. read_csv(): comma separated (CSV) files

2. read_tsv(): tab separated files

3. read_delim(): general delimited files

4. read_fwf(): fixed width files

5. read_table(): tabular files where columns are separated by white-space.

6. read_log(): web log files

- In many cases, these functions will just work: you supply the path to a file and you get a tibble back. The following example loads a sample file bundled with readr:

```{r,echo=TRUE,message=FALSE,warning=FALSE,comment=""}
library(datasets)
library(ggplot2)
library(readr)

mtcars <- read_csv(readr_example("mtcars.csv"))
head(mtcars)

```

- When you run read_csv() it prints out a column specification that gives the name and type of each column. That’s an important part of readr, which we’ll come back to in parsing a file.












